platform :android do
  lane :build do |options|
    build_task = (options[:bundle] ? "bundle" : "assemble")
    gradle(task: 'clean', project_dir: './android/')
    gradle(
      task: build_task,
      build_type: 'Release',
      project_dir: './android/'
    )
  end
  lane :incrementVersion do |options|
    increment_version_code(gradle_file_path: './android/app/build.gradle')
    bumpType = options[:bumpType]
    increment_version_name(gradle_file_path: './android/app/build.gradle', bump_type: bumpType )
    commit_android_version_bump(
      gradle_file_folder:"android/app"
    )
  end
  lane :releaseUploadPlayStore do |options|
    bumpType = options[:bumpType]
    incrementVersion(bumpType: bumpType)
    build(bundle: true)
    upload_to_play_store(track: 'beta')
  end
end